platform: "ensemble"
max_batch_size: 16

input [
  {
    name: "AUDIO_CHUNK"
    data_type: TYPE_INT32
    dims: [ 3200, 1 ]
  }
]

output [
  {
    name: "logprobs"
    data_type: TYPE_FP32
    dims: [ 13, 35 ]
  }
]

ensemble_scheduling {
  step [
    {
      model_name: "preprocessing"
      model_version: -1
      input_map { key: "audio_data" value: "AUDIO_CHUNK" }
      output_map { key: "DALI_OUTPUT_0" value: "signal" }
    },
    {
      model_name: "streaming_acoustic"
      model_version: -1
      input_map { key: "signal" value: "signal" }
      output_map { key: "logprobs" value: "logprobs" }
    }
  ]
}
