name: "model"
platform: "tensorrt_plan"
max_batch_size: 16

input: [
  {
    name: "length"
    data_type: TYPE_INT64
    dims: [ ]
  },
  {
    name: "audio_signal"
    data_type: TYPE_FP32
    dims: [ 64, -1 ]
  }
]

output: [
  {
    name: "decoder_logprobs"
    data_type: TYPE_FP32
    dims: [ -1, 35 ]
  }
]

sequence_batching {
  max_sequence_idle_microseconds: 15000000
  oldest {
    max_queue_delay_microseconds: 10000
    max_candidate_sequences: 4096
  }

  state: [
    {
      input_name: "cache_last_chan_len"
      output_name: "cache_last_chan_len_next"
      data_type: TYPE_INT32
      dims: [ 1 ]
      initial_state: {
        name: "cache_last_chan_len_initial"
        data_type: TYPE_INT32
        dims: [ 1 ]
        zero_data: true
      }
    },
    {
      input_name: "cache_last_channel"
      output_name: "cache_last_channel_next"
      data_type: TYPE_FP16
      dims: [ 32, 8, 50 ]
      initial_state: {
        name: "cache_last_channel_initial"
        data_type: TYPE_FP16
        dims: [ 32, 8, 50 ]
        zero_data: true
      }
    },
    {
      input_name: "cache_last_time"
      output_name: "cache_last_time_next"
      data_type: TYPE_FP16
      dims: [ 18, 384, 30 ]
      initial_state: {
        name: "cache_last_time_initial"
        data_type: TYPE_FP16
        dims: [ 18, 384, 30 ]
        zero_data: true
      }
    }
  ]
}

instance_group: [
  { count: 1 kind: KIND_GPU gpus: [ 0 ] }
]
