name: "model"
platform: "tensorrt_plan"
max_batch_size: 16

input: [
  {
    name: "length"
    data_type: TYPE_INT64
    dims: [1]
    reshape: {
      shape: [ ]
    }
  },
  {
    name: "audio_signal"
    data_type: TYPE_FP32
    dims: [ 64, -1 ]
  }
]

output [
  {
    name: "decoder_logprobs"
    data_type: TYPE_FP32
    dims: [ -1, 35 ]
  }
]

sequence_batching {
  max_sequence_idle_microseconds: 15000000
  oldest {
    max_queue_delay_microseconds: 10000
    max_candidate_sequences: 4096
  }

  state [
    {
      input_name: "state"
      output_name: "state_next"
      data_type: TYPE_FP16
      dims: [ 219729 ]
      initial_state: {
        name: "state_initial"
        data_type: TYPE_FP16
        dims: [ 219729 ]
        zero_data: true
      }
    }
  ]
}

instance_group [
  { count: 1 kind: KIND_GPU gpus: [0] }
]
