backend: "dali"
max_batch_size: 16
default_model_filename: "features_8k.py"

# For debugging, I strongly suggest disabling dynamic batching temporarily:
# dynamic_batching { preserve_ordering: true }

instance_group [{ count: 1 kind: KIND_GPU }]

input [
  {
    name: "audio_data"
    data_type: TYPE_INT32
    dims: [ 3200, 1 ]
  }
]

output [
  {
    name: "DALI_OUTPUT_0"
    data_type: TYPE_FP16
    dims: [ 40, 64 ]
  }
]
